const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';
const FETCH_USER_LOGIN = 'FETCH_USER_LOGIN';
const FETCH_USER_LOGOUT = 'FETCH_USER_LOGOUT';

export {
    FETCH_USERS_REQUEST,
    FETCH_USERS_SUCCESS,
    FETCH_USERS_ERROR,
    FETCH_USER_LOGIN,
    FETCH_USER_LOGOUT,
};
