const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

const FETCH_USER_LOGIN_REQUEST = 'FETCH_USER_LOGIN_REQUEST';
const FETCH_USER_LOGIN_SUCCESS = 'FETCH_USER_LOGIN_SUCCESS';
const FETCH_USER_LOGIN_ERROR = 'FETCH_USER_LOGIN_ERROR';

const FETCH_USER_LOGOUT_REQUEST = 'FETCH_USER_LOGOUT_REQUEST';
const FETCH_USER_LOGOUT_SUCCESS = 'FETCH_USER_LOGOUT_SUCCESS';
const FETCH_USER_LOGOUT_ERROR = 'FETCH_USER_LOGOUT_ERROR';

export {
    FETCH_USERS_REQUEST,
    FETCH_USERS_SUCCESS,
    FETCH_USERS_ERROR,
    FETCH_USER_LOGIN_REQUEST,
    FETCH_USER_LOGIN_SUCCESS,
    FETCH_USER_LOGIN_ERROR,
    FETCH_USER_LOGOUT_REQUEST,
    FETCH_USER_LOGOUT_SUCCESS,
    FETCH_USER_LOGOUT_ERROR,
};
